### ISSUE TITLE
Exception reading from http://localhost:10240

### ISSUE THREAD

**Issue by Vali5681** [ogrebenyuk/compilerexplorer#10]
Hey, 

When trying to use Compiler Explorer, I am getting this error : **"Exception reading from http://localhost:10240: Connect to localhost:10240 [localhost/127.0.0.1] failed: Connection refused: connect".**

I am using CLion 2019.2.3. Could you guide me through how to solve this issue?
I haven't seen any instalation guide anywhere, so I am somewhat confused at what I am doing wrong.

Image below:
![image](https://user-images.githubusercontent.com/6222937/83942741-b2b19f80-a7f6-11ea-9a50-0d4ef28a3447.png)

**Comment by tiziw** [comment]
You either need to run a local server compiler-explorer server (See https://github.com/compiler-explorer/compiler-explorer) or you can use an existing server. If you want to use an existing server, (f.e. https://godbolt.org hosted by the original devs). Click the settings button on the Compiler Explorer sidebar and set your server (in this case, https://godbolt.org). Then it should work, maybe you have to do 'Reset and Reload' first (also under the settings button).

Maybe it's an idea for the dev to set the default server to https://godbolt.org? Most people that use this plugin will probably use it for x86_64 and not for another platform, in that case the godbolt server would be ideal. It would also make the plugin work straight away without any configuration.

**Comment by ogrebenyuk** [comment]
The default URL is "http://localhost:10240", and I made it this way for privacy. This plugin allows one to explore the code of existing projects "in place" so to say - in their IDE where they are developing it.
Many organizations would be VERY unhappy if their source code was constantly leaking to an outside server by developers.

**Comment by tiziw** [comment]
That's a good point. It's not very clear from the start though, how/what you're supposed to configure. It took me a bit of time to figure how to configure it. Wouldn't it be the best of both worlds, if you add a setup dialog after the plugin is installed? That should state clearly how to use the plugin, namely to either run a local compiler-explorer instance (with a link to the guide) or that you can use an 'official' existing one (godbolt), with a warning that the compiler-explorer instance can see the source code of the project you're analysing.

**Comment by ogrebenyuk** [comment]
Thanks, that's an excellent suggestion. I will add a notification that would show up on first use.

**Comment by Vali5681** [comment]
> You either need to run a local server compiler-explorer server (See https://github.com/compiler-explorer/compiler-explorer) or you can use an existing server. If you want to use an existing server, (f.e. https://godbolt.org hosted by the original devs). Click the settings button on the Compiler Explorer sidebar and set your server (in this case, https://godbolt.org). Then it should work, maybe you have to do 'Reset and Reload' first (also under the settings button).
> 
> Maybe it's an idea for the dev to set the default server to https://godbolt.org? Most people that use this plugin will probably use it for x86_64 and not for another platform, in that case the godbolt server would be ideal. It would also make the plugin work straight away without any configuration.

Thank you very much for the explanation. By addding https://godbolt.org/ address, it works as expected.



> Thanks, that's an excellent suggestion. I will add a notification that would show up on first use.

This would be really appreciated by the non-initiated.

My specific issue is solved, so I am going to Close it.
