### ISSUE TITLE
[request] Stop using the "exe" returned from /api/compilers

### ISSUE THREAD

**Issue by partouf** [ogrebenyuk/compilerexplorer#12]
We've been overhauling our `/api/compilers` a bit to return fewer fields by default.
I see you're using the `exe` property, but it's not _really_ used.

We've kept the exe field for now, but it would be really nice if we could remove it and not depend on it anymore.

No worries if you don't have the time, get back to me whenever you do. And then eventually we can change the API once again to remove this field.

**Comment by ogrebenyuk** [comment]
I have rolled out a new version of the plugin that does not use "exe" anymore. Thanks for the heads up!

**Comment by partouf** [comment]
Thanks!
