### ISSUE TITLE
Can't download from Jetbrains Marketplace?

### ISSUE THREAD

**Issue by 13steinj** [ogrebenyuk/compilerexplorer#15]
This is an odd one. Quite literally, seemingly only this plugin, its installation page refuses to load within CLion > Settings > Plugins > Marketplace

![image](https://user-images.githubusercontent.com/10525230/105555125-bbe47380-5cd6-11eb-8582-57103f868f19.png)

Weirder: this is the only plugin that's exhibiting this behavior. Some other plugins take a few seconds to load, sure, but this one, just refuses. I've left it for over an hour at this point.

![image](https://user-images.githubusercontent.com/10525230/105555215-eafae500-5cd6-11eb-9f93-7080152df104.png)

Of course I know we can install from source and such, and I'm no stranger to that (though to be honest, I don't want to). But if I'm not the only person this is happening to, ought to let you know.

**Comment by 13steinj** [comment]
currently open and waiting for the plugin to load in the marketplace for 3 hours, still waiting

**Comment by ogrebenyuk** [comment]
Sorry, I don't see that problem. Everything works as expected to me. I must be something on your side.

**Comment by 13steinj** [comment]
I have no idea what the cause was. This was occurring in a manner that was operating system and network agnostic (though it seemed somehow bound to my Jetbrains account). Though when the 2021.1 update released, it seems to have resolved. I can only assume Jetbrains had some bug with specific accounts that fit some pattern that had since been fixed.
