### ISSUE TITLE
Cannot determine compiler version (WSL)

### ISSUE THREAD

**Issue by lmreia** [ogrebenyuk/compilerexplorer#2]
I am trying to use the Compiler Explorer with Windows Subsystem for Linux.
I am able to access http://localhost:10240/ and use the Compiler Explorer in the browser, and the plugin for Clion is able to stabilish the connection, but when I try to use the plugin, it shows this message:

Cannot determine compiler version:
C:\usr\bin\g++ -v
Exception: Cannot run program "C:\usr\bin\g++" (in directory "\usr\bin"): CreateProcess error=2

It seems it is trying to use the "C:\usr\bin\g++" path instead of the "\usr\bin\g++" inside of the WSL. I am using Clion 2019.2 EAP (build #CL-192.5587.18)

**Comment by Organic-Code** [comment]
@ogrebenyuk  Any chance of this being fixed in the near future ?

**Comment by ogrebenyuk** [comment]
I will try to look at it this weekend.

**Comment by Organic-Code** [comment]
Nice thank you

**Comment by Organic-Code** [comment]
Any updates ?

**Comment by ogrebenyuk** [comment]
No, sorry. I just don't have the bandwidth to investigate this at the moment.

**Comment by overridecheese** [comment]
HI, I had the same problem，When i open the Compiler Explorer Tool Window,  got the following error:

```
Cannot determine compiler version:
C:\usr\bin\c++ -v
Exception: Cannot run program "C:\usr\bin\c++" (in directory "\usr\bin"): CreateProcess error=2
```

I am running CLion 2021.2 in windows 10, The default CLion ToolChain type is WSL, CLion automatically detects and fills the following ToolChain fields:

- Envorionment: Ubuntu 20.04.2 
- C++ Compiler: /usr/bin/c++.

**Comment by ogrebenyuk** [comment]
All forms of remote compilation are now supported: WSL, SSH, Space.
