### ISSUE TITLE
CLion 2022.3.3 does not terminate after updating Compiler Explorer to 1.19

### ISSUE THREAD

**Issue by intelfx** [ogrebenyuk/compilerexplorer#23]
Hi,

(I'm not sure if this bug report is actually relevant to Compiler Explorer — if it's not, I apologize in advance.)

### version

I'm using CLion 2022.3.3 with JetBrains runtime 17.0.6+1-b653.34 amd64 on an Arch Linux installation.

### problem

After updating the Compiler Explorer plugin to 1.19 (it was the only plugin with an update), my CLion does not fully terminate (i. e. I close the window to apply the update and the CLion process never exits). If I terminate the process with SIGTERM or SIGKILL, on the next run the plugin appears to remain at 1.18.

If I do not upgrade the plugin, CLion terminates normally.

**Comment by ogrebenyuk** [comment]
Sorry, I couldn't reproduce the problem. I have just tried it on both Windows and Linux, and the plugin update works as expected.

**Comment by intelfx** [comment]
Does not happen with 1.20 anymore. Not sure why.
