### ISSUE TITLE
Ignoring certain compiler flags

### ISSUE THREAD

**Issue by tiziw** [ogrebenyuk/compilerexplorer#9]
Hi, first of all, great plugin. It's made checking the assembly output a piece of cake. I have a minor inconvenience when I compile my code with the "-m32" flag to compile my code to a 32-bit binary. I get a compiler error on any platform other than x86-64. This is obvious since only x86 supports that flag, however there's no option to ignore it in any way (as far as I know).

Example:
![image](https://user-images.githubusercontent.com/34965470/83928086-ccb79780-a78e-11ea-846f-8da98296baa2.png)

Is there a way that filters can be added in the plugin config to ignore certain flags? 

Thanks for reading!

**Comment by ogrebenyuk** [comment]
Hi,

Thanks for your interest in the plugin.

I have uploaded a new version of the plugin with this feature. Once approved by JetBrains moderators, you will be able to upgrade to it.

Then you will see the "Ignore compiler switches" field in the File -> Settings -> Build, Execution, Deployment -> Compiler Explorer page.

**Comment by tiziw** [comment]
Works perfect! Great job and thanks!
